Externally Populated Spin Deck and Gate URL's for Saas
OpsMx/enterprise-spinnaker pull request #82
Opened 2021-01-25 12:34 UTC by lakkireddys-opsmx

2021-01-25 17:32 UTC, lakkireddys-opsmx commented
Externally Populated Spin Deck and Gate URL's for Saas

Please review the changes made.

2021-01-25 17:37 UTC, abhinayopsmx requested changes
Please think in user's perspective on how we can fully automate the process. User should just give the necessary urls in the values.yaml and the same urls should be used everywhere. Helm installation should also create ingress resources automatically by using the urls and annotations specified in the values.yaml

2021-01-25 17:37 UTC, abhinayopsmx commented on charts/oes/values.yaml
> +installationMode: OES
Why did we change the default installation mode?

2021-01-25 17:37 UTC, abhinayopsmx commented on charts/oes/values.yaml
> +      apioverrideBaseUrl: /ofc
These urls should be indicative of how actual urls should be. and we should make helm chart behave in such a way that same urls are used in ingress resources that needs to be created.

2021-02-24 20:14 UTC, abhinaybyrisetty commented
Handled these in OES 3.5 release in an alternative way

2021-02-24 20:14 UTC, closed without merging